### ISSUE TITLE
Translatable - предложения

### ISSUE THREAD

**Issue by austyuzhaninov** [visual-ideas/moonshine-spatie-translatable#1]
Добрый день, на текущий момент нашел следующие баги:
Предположим есть ресурс:
![image](https://user-images.githubusercontent.com/38152348/233170689-72c4ccdf-0ab7-4637-8d96-ac14dd66cc25.png)

1) При редактировании не сохраняется/передается ключ, как следствие данные не отображаются.
![image](https://user-images.githubusercontent.com/38152348/233171010-73466c24-65df-4905-8345-2ec410af9ff0.png)

2) При создании dropdown улетает под слой
![image](https://user-images.githubusercontent.com/38152348/233171127-268a2c6e-9281-49a7-a209-f0945c2d950f.png)

3) Текущий массив со списком языков имеет protected свойство и в списке всегда отображается "полотно" языков (они же ключи) что не совсем удобно. priorityLanguages немного не то. Есть ли вариант вынести например в конфигурацию, массив языков по умолчанию, если такой не определён предоставить все языки.

**Comment by austyuzhaninov** [comment]
Так же были обнаружены следующие ошибки в поведении:

Не выбирается с первого раза нужный ключ, воспроизведение ошибки:
1) Добавляем строку (нажимаем Добавить)
![image](https://user-images.githubusercontent.com/38152348/233360836-84a3876c-a60b-4a34-98bf-8a105060ae24.png)
2) Выбираем нужную локаль (допустим RU)
![image](https://user-images.githubusercontent.com/38152348/233360957-7bb281dd-aafe-4bd6-b55f-453dbd4f2116.png)
3) После этого значение остаётся пустым
![image](https://user-images.githubusercontent.com/38152348/233361078-8aa93a7d-a178-4180-831a-2132b26fa174.png)

Только со второго раза удаётся поставить значение
![image](https://user-images.githubusercontent.com/38152348/233361158-6a8b7381-743d-45b1-9b50-3e50552eb0c9.png)

Значение из одной локали(на скриншоте RU), сразу передаётся в другую (на скриншоте EN)
![image](https://user-images.githubusercontent.com/38152348/233361471-0f13bb46-3e3e-4c33-826e-b93be8f04c2d.png)

Так же и в обратную сторону
![image](https://user-images.githubusercontent.com/38152348/233361593-20847e0f-650c-48ab-afa0-7f6ba0e31e4c.png)
После снятия курсора с поля(селекта)
![image](https://user-images.githubusercontent.com/38152348/233361753-208af924-f7bb-4d98-9c21-c6294a47f05b.png)

**Comment by austyuzhaninov** [comment]
Данное поведение на конфигурации:

```
laravel/framework": "10.8.0",
"spatie/laravel-translatable": "6.4.0",
"moonshine/moonshine": "1.53.3"
"visual-ideas/moonshine-spatie-translatable": "1.0.0"
```

**Comment by alexvenga** [comment]
Обновите, пофиксил вашу проблему, и привел отображение на индексе и на деталях в вид как было раньше
